# Generated by Django 5.2.5 on 2025-08-29 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('scraper', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('date_posted', models.DateField()),
                ('date_available', models.CharField(max_length=50)),
                ('category_type', models.CharField(blank=True, max_length=100)),
                ('bedroom_count', models.IntegerField(blank=True, null=True)),
                ('bathroom_count', models.FloatField(blank=True, null=True)),
                ('utilities', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
